### ISSUE TITLE
Why don't you bundle all required components with the download?

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/CaTRoX_QWR#3]
As title!

**Comment by TheQwertiest** [comment]
There are several reasons:
1. Some developers do not approve of rehosting their work. Not that I had problems with this project specifically, but I had complaints about that on my other project (which is not on github though :P). 
2. Some people have paranoia and complain about including the actual binaries instead of links to the official hosting, because they suspect that some malicious code was injected in the redistributed binaries. Which is annoying -_-

But I might reconsider it once I conquer my laziness and get the permission to rehost from all (active) component developers.

**Comment by marc2k3** [comment]
Fair enough.
